---
name: "Shell Executor"
guid: "eb5d7894-8eef-4b36-aa7f-5d124e828ce1"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "YourName"
overview: "Execute shell scripts on plugin initialization"
description: >
  This plugin allows you to execute shell scripts when Jellyfin starts.
  You can edit the script content through the plugin configuration interface.
category: "General"
artifacts:
  - "JellyfinShellExecutor.dll"
changelog: >
  ### 1.0.0.0
  - Initial release